### PR TITLE
Always returning true in doesChangeLogTableExist() since the check ca…

### PR DESCRIPTION
**Pull request by tomusiaka**
…uses Oracle bug to leave open cursors and the check is not really necessary since the minimum Cascade version to upgrade from should already have the change log table. #409

### CODE REVIEW

**Comment by bradical** [comment]
Having trouble seeing the changes in here since it looks like most of the file has been changed. Should I just focus on that one method?

**Comment by tomusiaka** [comment]
Yes, [here](https://github.com/hannonhill/liquibase/commit/500a88abd51977bc55ef119cd015361f3e7dbaef#diff-0b97a86f2a5f17da8c54f27badebb235L606) is what really changed.

**Comment by bradical** [comment]
Got it. Thanks!

**Comment by tomusiaka** [comment]
Changes from this pull request are already included in Cacsade project. Merging to keep it in sync with Cascade.

**Pull request merged**
